"""HTML report generation for Excelion Forge validation results.

This module is Blender-independent. It takes the dict produced by
serializer.session_to_dict() and returns a complete HTML string.
"""

from __future__ import annotations

from excelion_forge.core.serializer import session_to_dict


_SEVERITY_COLOR: dict[str, str] = {
    "ERROR": "#c0392b",
    "WARNING": "#d35400",
    "INFO": "#2980b9",
}

_SEVERITY_BG: dict[str, str] = {
    "ERROR": "#fdf0ef",
    "WARNING": "#fdf5ec",
    "INFO": "#eef4fb",
}

_SEVERITY_BADGE_BG: dict[str, str] = {
    "ERROR": "#e74c3c",
    "WARNING": "#f39c12",
    "INFO": "#3498db",
}


def generate_html(data: dict) -> str:
    """Generate a standalone HTML report string from serialized validation data.

    Args:
        data: Dictionary as produced by serializer.session_to_dict().

    Returns:
        A complete, self-contained UTF-8 HTML string.
    """
    summary = data.get("summary", {})
    issues = data.get("issues", [])
    target = data.get("target_object", "") or "—"
    exported_at = data.get("exported_at", "")
    version = data.get("excelion_forge_version", "")

    issue_rows = "\n".join(_render_issue_row(i) for i in issues)
    no_issues_msg = (
        ""
        if issues
        else '<tr><td colspan="7" style="text-align:center;padding:16px;color:#27ae60;">'
             "✓ All validation checks passed.</td></tr>"
    )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Excelion Forge — Validation Report</title>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #f4f6f8;
      color: #2c3e50;
      margin: 0;
      padding: 24px;
    }}
    .container {{ max-width: 1000px; margin: 0 auto; }}
    header {{
      background: #1a1a2e;
      color: #e8e8e8;
      padding: 20px 24px;
      border-radius: 8px;
      margin-bottom: 20px;
    }}
    header h1 {{ margin: 0 0 4px; font-size: 1.4rem; }}
    header .meta {{ font-size: 0.8rem; color: #aaa; }}
    .summary {{
      display: flex;
      gap: 12px;
      margin-bottom: 20px;
      flex-wrap: wrap;
    }}
    .badge {{
      padding: 10px 18px;
      border-radius: 6px;
      color: white;
      font-weight: 600;
      font-size: 1rem;
      min-width: 100px;
      text-align: center;
    }}
    .badge-total {{ background: #555; }}
    .badge-error {{ background: #e74c3c; }}
    .badge-warning {{ background: #f39c12; }}
    .badge-info {{ background: #3498db; }}
    table {{
      width: 100%;
      border-collapse: collapse;
      background: white;
      border-radius: 8px;
      overflow: hidden;
      box-shadow: 0 1px 3px rgba(0,0,0,0.12);
    }}
    th {{
      background: #2c3e50;
      color: white;
      padding: 10px 12px;
      text-align: left;
      font-size: 0.85rem;
      font-weight: 600;
    }}
    td {{
      padding: 9px 12px;
      font-size: 0.85rem;
      border-bottom: 1px solid #ecf0f1;
      vertical-align: top;
    }}
    .sev {{
      font-weight: 700;
      font-size: 0.75rem;
      padding: 3px 7px;
      border-radius: 4px;
      color: white;
      white-space: nowrap;
    }}
    .sev-ERROR   {{ background: #e74c3c; }}
    .sev-WARNING {{ background: #f39c12; }}
    .sev-INFO    {{ background: #3498db; }}
    .fix-yes {{ color: #27ae60; font-weight: 600; }}
    .fix-no  {{ color: #95a5a6; }}
    tr:last-child td {{ border-bottom: none; }}
    tr:hover td {{ background: #f9fbfc; }}
    footer {{
      margin-top: 16px;
      font-size: 0.75rem;
      color: #95a5a6;
      text-align: center;
    }}
  </style>
</head>
<body>
<div class="container">
  <header>
    <h1>⚙ Excelion Forge — Validation Report</h1>
    <div class="meta">
      Target: <strong>{target}</strong> &nbsp;|&nbsp;
      Exported: {exported_at} &nbsp;|&nbsp;
      Forge v{version}
    </div>
  </header>

  <div class="summary">
    <div class="badge badge-total">Total: {summary.get("total", 0)}</div>
    <div class="badge badge-error">Errors: {summary.get("errors", 0)}</div>
    <div class="badge badge-warning">Warnings: {summary.get("warnings", 0)}</div>
    <div class="badge badge-info">Infos: {summary.get("infos", 0)}</div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Severity</th>
        <th>Code</th>
        <th>Rule</th>
        <th>Message</th>
        <th>Location</th>
        <th>Suggestion</th>
        <th>Auto Fix</th>
      </tr>
    </thead>
    <tbody>
      {issue_rows}
      {no_issues_msg}
    </tbody>
  </table>

  <footer>Generated by Excelion Forge v{version}</footer>
</div>
</body>
</html>"""


def _render_issue_row(issue: dict) -> str:
    """Render a single HTML table row for an issue dict."""
    sev = issue.get("severity", "")
    sev_class = f"sev sev-{sev}" if sev in _SEVERITY_BG else "sev"

    loc_type = issue.get("location_type", "none")
    if loc_type == "bone":
        location = f"Bone: {issue.get('bone_name', '')}"
    elif loc_type == "object":
        location = f"Object: {issue.get('object_name', '')}"
    else:
        location = "—"

    fix_html = (
        '<span class="fix-yes">✓ Yes</span>'
        if issue.get("has_fix")
        else '<span class="fix-no">—</span>'
    )
    suggestion = issue.get("suggestion", "") or "—"
    code = _escape(issue.get("code", ""))
    rule = _escape(issue.get("rule_name", ""))
    message = _escape(issue.get("message", ""))
    location = _escape(location)
    suggestion = _escape(suggestion)

    return (
        f"<tr>"
        f'<td><span class="{sev_class}">{sev}</span></td>'
        f"<td><code>{code}</code></td>"
        f"<td>{rule}</td>"
        f"<td>{message}</td>"
        f"<td>{location}</td>"
        f"<td>{suggestion}</td>"
        f"<td>{fix_html}</td>"
        f"</tr>"
    )


def _escape(text: str) -> str:
    """Escape HTML special characters in text."""
    return (
        text
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def export_html(session: object, filepath: str, target_name: str = "") -> None:
    """Serialize session to HTML and write to filepath as UTF-8.

    Args:
        session: EFORGE_PG_validation_session or compatible object.
        filepath: Absolute path for the output file.
        target_name: Name of the armature object being validated.
    """
    data = session_to_dict(session, target_name)
    html = generate_html(data)
    with open(filepath, "w", encoding="utf-8") as fp:
        fp.write(html)


def default_html_filename() -> str:
    """Return a timestamped default filename for HTML export."""
    from datetime import datetime
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    return f"forge_validation_{ts}.html"
