[database]
host=localhost
port=5432
username=admin
password=secret
database=mydb

[upbit]
access_key = Y3RFJh4W3IZxx3eVhbzowLNllkNe2lfx5U2qAPxi
secret_key = oG8VliaBzzrbNS7WMydvTJ3KUr4s0sCLZwPZhJ81
;server_url = https://api.upbit.com