PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS TB_SYSTEM_SETTING (
    SETTING_KEY TEXT PRIMARY KEY,
    SETTING_VALUE TEXT NOT NULL,
    VALUE_TYPE TEXT NOT NULL,
    DESCRIPTION TEXT,
    UPDATED_AT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_CODE_GROUP (
    CODE_GROUP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    GROUP_KEY TEXT NOT NULL UNIQUE,
    GROUP_NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    IS_ACTIVE INTEGER NOT NULL DEFAULT 1 CHECK (IS_ACTIVE IN (0,1))
);

CREATE TABLE IF NOT EXISTS TB_CODE (
    CODE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CODE_GROUP_ID INTEGER NOT NULL,
    CODE_KEY TEXT NOT NULL,
    CODE_NAME TEXT NOT NULL,
    SORT_ORDER INTEGER NOT NULL DEFAULT 0,
    IS_ACTIVE INTEGER NOT NULL DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
    DESCRIPTION TEXT,
    FOREIGN KEY (CODE_GROUP_ID) REFERENCES TB_CODE_GROUP(CODE_GROUP_ID),
    UNIQUE (CODE_GROUP_ID, CODE_KEY)
);

CREATE TABLE IF NOT EXISTS TB_ITEM (
    ITEM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ITEM_CODE TEXT NOT NULL UNIQUE,
    ITEM_NAME TEXT NOT NULL,
    ITEM_CATEGORY_CODE TEXT NOT NULL,
    GRADE_ID INTEGER,
    UNIT_CODE TEXT NOT NULL,
    IS_ACTIVE INTEGER NOT NULL DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
    CREATED_AT TEXT NOT NULL,
    UPDATED_AT TEXT NOT NULL,
    FOREIGN KEY (GRADE_ID) REFERENCES TB_ITEM_GRADE(ITEM_GRADE_ID)
);

CREATE TABLE IF NOT EXISTS TB_ITEM_GRADE (
    ITEM_GRADE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    GRADE_CODE TEXT NOT NULL UNIQUE,
    GRADE_NAME TEXT NOT NULL,
    IS_ACTIVE INTEGER NOT NULL DEFAULT 1 CHECK (IS_ACTIVE IN (0,1))
);

CREATE TABLE IF NOT EXISTS TB_PARTNER (
    PARTNER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PARTNER_CODE TEXT NOT NULL UNIQUE,
    PARTNER_NAME TEXT NOT NULL,
    PARTNER_TYPE_CODE TEXT NOT NULL,
    IS_ACTIVE INTEGER NOT NULL DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
    CREATED_AT TEXT NOT NULL,
    UPDATED_AT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_PARTNER_ITEM (
    PARTNER_ITEM_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PARTNER_ID INTEGER NOT NULL,
    ITEM_ID INTEGER NOT NULL,
    PARTNER_ITEM_CODE TEXT,
    PARTNER_ITEM_NAME TEXT,
    IS_ACTIVE INTEGER NOT NULL DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
    FOREIGN KEY (PARTNER_ID) REFERENCES TB_PARTNER(PARTNER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM(ITEM_ID)
);

CREATE TABLE IF NOT EXISTS TB_PRICE (
    PRICE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PARTNER_ID INTEGER NOT NULL,
    ITEM_ID INTEGER NOT NULL,
    UNIT_PRICE NUMERIC NOT NULL CHECK (UNIT_PRICE >= 0),
    EFFECTIVE_FROM TEXT NOT NULL,
    PRIORITY INTEGER NOT NULL DEFAULT 0,
    IS_ACTIVE INTEGER NOT NULL DEFAULT 1 CHECK (IS_ACTIVE IN (0,1)),
    CREATED_AT TEXT NOT NULL,
    UPDATED_AT TEXT NOT NULL,
    FOREIGN KEY (PARTNER_ID) REFERENCES TB_PARTNER(PARTNER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM(ITEM_ID)
);

CREATE TABLE IF NOT EXISTS TB_SALES_ORDER (
    SALES_ORDER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DOCUMENT_NO TEXT NOT NULL UNIQUE,
    ORDER_DATE TEXT NOT NULL,
    PARTNER_ID INTEGER NOT NULL,
    DUE_DATE TEXT,
    STATUS_CODE TEXT NOT NULL,
    NOTE TEXT,
    CREATED_AT TEXT NOT NULL,
    UPDATED_AT TEXT NOT NULL,
    FOREIGN KEY (PARTNER_ID) REFERENCES TB_PARTNER(PARTNER_ID)
);

CREATE TABLE IF NOT EXISTS TB_SALES_ORDER_DETAIL (
    SALES_ORDER_DETAIL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SALES_ORDER_ID INTEGER NOT NULL,
    ITEM_ID INTEGER NOT NULL,
    PARTNER_ITEM_ID INTEGER,
    PRICE_ID INTEGER,
    ORDER_QTY NUMERIC NOT NULL CHECK (ORDER_QTY > 0),
    APPLIED_UNIT_PRICE NUMERIC NOT NULL CHECK (APPLIED_UNIT_PRICE >= 0),
    AMOUNT NUMERIC NOT NULL CHECK (AMOUNT >= 0),
    DUE_DATE TEXT,
    NOTE TEXT,
    FOREIGN KEY (SALES_ORDER_ID) REFERENCES TB_SALES_ORDER(SALES_ORDER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM(ITEM_ID),
    FOREIGN KEY (PARTNER_ITEM_ID) REFERENCES TB_PARTNER_ITEM(PARTNER_ITEM_ID),
    FOREIGN KEY (PRICE_ID) REFERENCES TB_PRICE(PRICE_ID)
);

CREATE TABLE IF NOT EXISTS TB_PURCHASE_ORDER (
    PURCHASE_ORDER_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DOCUMENT_NO TEXT NOT NULL UNIQUE,
    ORDER_DATE TEXT NOT NULL,
    PARTNER_ID INTEGER NOT NULL,
    DUE_DATE TEXT,
    STATUS_CODE TEXT NOT NULL,
    NOTE TEXT,
    CREATED_AT TEXT NOT NULL,
    UPDATED_AT TEXT NOT NULL,
    FOREIGN KEY (PARTNER_ID) REFERENCES TB_PARTNER(PARTNER_ID)
);

CREATE TABLE IF NOT EXISTS TB_PURCHASE_ORDER_DETAIL (
    PURCHASE_ORDER_DETAIL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PURCHASE_ORDER_ID INTEGER NOT NULL,
    ITEM_ID INTEGER NOT NULL,
    PRICE_ID INTEGER,
    ORDER_QTY NUMERIC NOT NULL CHECK (ORDER_QTY > 0),
    APPLIED_UNIT_PRICE NUMERIC NOT NULL CHECK (APPLIED_UNIT_PRICE >= 0),
    AMOUNT NUMERIC NOT NULL CHECK (AMOUNT >= 0),
    DUE_DATE TEXT,
    NOTE TEXT,
    FOREIGN KEY (PURCHASE_ORDER_ID) REFERENCES TB_PURCHASE_ORDER(PURCHASE_ORDER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM(ITEM_ID),
    FOREIGN KEY (PRICE_ID) REFERENCES TB_PRICE(PRICE_ID)
);

CREATE TABLE IF NOT EXISTS TB_PRODUCTION (
    PRODUCTION_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DOCUMENT_NO TEXT NOT NULL UNIQUE,
    PRODUCTION_DATE TEXT NOT NULL,
    STATUS_CODE TEXT NOT NULL,
    NOTE TEXT,
    CREATED_AT TEXT NOT NULL,
    UPDATED_AT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_PRODUCTION_DETAIL (
    PRODUCTION_DETAIL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PRODUCTION_ID INTEGER NOT NULL,
    ITEM_ID INTEGER NOT NULL,
    PRODUCTION_QTY NUMERIC NOT NULL CHECK (PRODUCTION_QTY >= 0),
    DEFECT_QTY NUMERIC NOT NULL DEFAULT 0 CHECK (DEFECT_QTY >= 0),
    FOREIGN KEY (PRODUCTION_ID) REFERENCES TB_PRODUCTION(PRODUCTION_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM(ITEM_ID)
);

CREATE TABLE IF NOT EXISTS TB_LOT (
    LOT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MK_LOT_NO TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    UPDATED_AT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS TB_PARTNER_LOT (
    PARTNER_LOT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PARTNER_ID INTEGER NOT NULL,
    PARTNER_LOT_NO TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    UPDATED_AT TEXT NOT NULL,
    FOREIGN KEY (PARTNER_ID) REFERENCES TB_PARTNER(PARTNER_ID)
);

CREATE TABLE IF NOT EXISTS TB_LOT_PARTNER_LOT (
    LOT_ID INTEGER NOT NULL,
    PARTNER_LOT_ID INTEGER NOT NULL,
    CREATED_AT TEXT NOT NULL,
    PRIMARY KEY (LOT_ID, PARTNER_LOT_ID),
    FOREIGN KEY (LOT_ID) REFERENCES TB_LOT(LOT_ID),
    FOREIGN KEY (PARTNER_LOT_ID) REFERENCES TB_PARTNER_LOT(PARTNER_LOT_ID)
);

CREATE TABLE IF NOT EXISTS TB_INOUT (
    INOUT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    DOCUMENT_NO TEXT NOT NULL UNIQUE,
    MOVEMENT_DATE TEXT NOT NULL,
    MOVEMENT_TYPE_CODE TEXT NOT NULL,
    PARTNER_ID INTEGER,
    SOURCE_TYPE_CODE TEXT,
    SOURCE_ID INTEGER,
    PRODUCTION_DATE TEXT,
    NOTE TEXT,
    STATUS_CODE TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    UPDATED_AT TEXT NOT NULL,
    FOREIGN KEY (PARTNER_ID) REFERENCES TB_PARTNER(PARTNER_ID)
);

CREATE TABLE IF NOT EXISTS TB_INOUT_DETAIL (
    INOUT_DETAIL_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    INOUT_ID INTEGER NOT NULL,
    ITEM_ID INTEGER NOT NULL,
    LOT_ID INTEGER,
    PARTNER_LOT_ID INTEGER,
    QUANTITY NUMERIC NOT NULL CHECK (QUANTITY > 0),
    UNIT_PRICE NUMERIC CHECK (UNIT_PRICE >= 0),
    AMOUNT NUMERIC CHECK (AMOUNT >= 0),
    FOREIGN KEY (INOUT_ID) REFERENCES TB_INOUT(INOUT_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES TB_ITEM(ITEM_ID),
    FOREIGN KEY (LOT_ID) REFERENCES TB_LOT(LOT_ID),
    FOREIGN KEY (PARTNER_LOT_ID) REFERENCES TB_PARTNER_LOT(PARTNER_LOT_ID)
);

CREATE TABLE IF NOT EXISTS TB_AUDIT_LOG (
    AUDIT_LOG_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ENTITY_NAME TEXT NOT NULL,
    ENTITY_ID INTEGER,
    ACTION_CODE TEXT NOT NULL,
    ACTOR TEXT,
    OCCURRED_AT TEXT NOT NULL,
    BEFORE_JSON TEXT,
    AFTER_JSON TEXT,
    NOTE TEXT
);

CREATE INDEX IF NOT EXISTS IX_INOUT_DATE
ON TB_INOUT(MOVEMENT_DATE);

CREATE INDEX IF NOT EXISTS IX_INOUT_DETAIL_ITEM
ON TB_INOUT_DETAIL(ITEM_ID);

CREATE INDEX IF NOT EXISTS IX_INOUT_DETAIL_LOT
ON TB_INOUT_DETAIL(LOT_ID, PARTNER_LOT_ID);

CREATE INDEX IF NOT EXISTS IX_AUDIT_ENTITY
ON TB_AUDIT_LOG(ENTITY_NAME, ENTITY_ID, OCCURRED_AT);
