INSERT OR IGNORE INTO TB_CODE_GROUP (GROUP_KEY,GROUP_NAME,DESCRIPTION) VALUES
('ITEM_CATEGORY','품목구분','원재료/반제품/완제품'),
('PARTNER_TYPE','거래처구분','고객/공급처'),
('INOUT_TYPE','입출고유형','재고 증감 업무유형'),
('DOCUMENT_STATUS','문서상태','업무 문서 상태'),
('AUDIT_ACTION','감사행위','변경 이력 행위');

INSERT OR IGNORE INTO TB_SYSTEM_SETTING (SETTING_KEY,SETTING_VALUE,VALUE_TYPE,DESCRIPTION,UPDATED_AT) VALUES
('DOC_NO.SALES_ORDER','SO-{yyyyMM}-{seq4}','TEXT','수주 문서번호 규칙','2026-10-01T00:00:00'),
('DOC_NO.PURCHASE_ORDER','PO-{yyyyMM}-{seq4}','TEXT','발주 문서번호 규칙','2026-10-01T00:00:00'),
('DOC_NO.PRODUCTION','PR-{yyyyMM}-{seq4}','TEXT','생산 문서번호 규칙','2026-10-01T00:00:00'),
('DOC_NO.INOUT','IO-{yyyyMM}-{seq4}','TEXT','입출고 문서번호 규칙','2026-10-01T00:00:00'),
('BACKUP.FULL_WEEKLY','1','BOOLEAN','주 1회 Full Backup 사용','2026-10-01T00:00:00');

INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'CUSTOMER','고객',10 FROM TB_CODE_GROUP WHERE GROUP_KEY='PARTNER_TYPE';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'SUPPLIER','공급처',20 FROM TB_CODE_GROUP WHERE GROUP_KEY='PARTNER_TYPE';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'BOTH','고객/공급처',30 FROM TB_CODE_GROUP WHERE GROUP_KEY='PARTNER_TYPE';

INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'RAW','원재료',10 FROM TB_CODE_GROUP WHERE GROUP_KEY='ITEM_CATEGORY';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'SEMI','반제품',20 FROM TB_CODE_GROUP WHERE GROUP_KEY='ITEM_CATEGORY';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'FINISHED','완제품',30 FROM TB_CODE_GROUP WHERE GROUP_KEY='ITEM_CATEGORY';

INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'IN','입고',10 FROM TB_CODE_GROUP WHERE GROUP_KEY='INOUT_TYPE';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'OUT','출고',20 FROM TB_CODE_GROUP WHERE GROUP_KEY='INOUT_TYPE';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'LOSS','LOSS',30 FROM TB_CODE_GROUP WHERE GROUP_KEY='INOUT_TYPE';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'OPENING','초기재고',5 FROM TB_CODE_GROUP WHERE GROUP_KEY='INOUT_TYPE';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'ADJUST','재고조정',40 FROM TB_CODE_GROUP WHERE GROUP_KEY='INOUT_TYPE';

INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'DRAFT','작성중',10 FROM TB_CODE_GROUP WHERE GROUP_KEY='DOCUMENT_STATUS';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'CONFIRMED','확정',20 FROM TB_CODE_GROUP WHERE GROUP_KEY='DOCUMENT_STATUS';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'CLOSED','완료',30 FROM TB_CODE_GROUP WHERE GROUP_KEY='DOCUMENT_STATUS';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'CANCELLED','취소',40 FROM TB_CODE_GROUP WHERE GROUP_KEY='DOCUMENT_STATUS';

INSERT OR IGNORE INTO TB_CODE_GROUP (GROUP_KEY,GROUP_NAME,DESCRIPTION) VALUES
('SOURCE_TYPE','원천유형','업무 문서 원천 유형'),
('ORDER_PROCESS_ACTION','수주발주 처리행위','수주/발주 처리 이력 행위');

INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'SALES_ORDER','수주',10 FROM TB_CODE_GROUP WHERE GROUP_KEY='SOURCE_TYPE';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'PURCHASE_ORDER','발주',20 FROM TB_CODE_GROUP WHERE GROUP_KEY='SOURCE_TYPE';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'PRODUCTION','생산',30 FROM TB_CODE_GROUP WHERE GROUP_KEY='SOURCE_TYPE';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'PRODUCTION_DEFECT','생산불량',40 FROM TB_CODE_GROUP WHERE GROUP_KEY='SOURCE_TYPE';

INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'PROCESS','처리',10 FROM TB_CODE_GROUP WHERE GROUP_KEY='ORDER_PROCESS_ACTION';

INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'CREATE','생성',10 FROM TB_CODE_GROUP WHERE GROUP_KEY='AUDIT_ACTION';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'UPDATE','수정',20 FROM TB_CODE_GROUP WHERE GROUP_KEY='AUDIT_ACTION';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'DEACTIVATE','비활성화',30 FROM TB_CODE_GROUP WHERE GROUP_KEY='AUDIT_ACTION';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'PROCESS','처리',40 FROM TB_CODE_GROUP WHERE GROUP_KEY='AUDIT_ACTION';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'CONFIRM','확정',50 FROM TB_CODE_GROUP WHERE GROUP_KEY='AUDIT_ACTION';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'CANCEL','취소',60 FROM TB_CODE_GROUP WHERE GROUP_KEY='AUDIT_ACTION';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'LOGICAL_DELETE','논리삭제',70 FROM TB_CODE_GROUP WHERE GROUP_KEY='AUDIT_ACTION';

INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'SALES_ORDER_CANCEL','수주취소',50 FROM TB_CODE_GROUP WHERE GROUP_KEY='SOURCE_TYPE';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'PRODUCTION_DEFECT','생산불량',40 FROM TB_CODE_GROUP WHERE GROUP_KEY='SOURCE_TYPE';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'REVERSE','반전처리',20 FROM TB_CODE_GROUP WHERE GROUP_KEY='ORDER_PROCESS_ACTION';
