INSERT OR IGNORE INTO TB_CODE_GROUP (GROUP_KEY,GROUP_NAME,DESCRIPTION) VALUES
('ITEM_CATEGORY','품목구분','원재료/반제품/완제품'),
('PARTNER_TYPE','거래처구분','고객/공급처'),
('INOUT_TYPE','입출고유형','재고 증감 업무유형'),
('DOCUMENT_STATUS','문서상태','업무 문서 상태'),
('AUDIT_ACTION','감사행위','변경 이력 행위');

INSERT OR IGNORE INTO TB_SYSTEM_SETTING (SETTING_KEY,SETTING_VALUE,VALUE_TYPE,DESCRIPTION,UPDATED_AT) VALUES
('DOC_NO.SALES_ORDER','SO-{yyyyMM}-{seq4}','TEXT','수주 문서번호 규칙','2026-10-01T00:00:00'),
('DOC_NO.PURCHASE_ORDER','PO-{yyyyMM}-{seq4}','TEXT','발주 문서번호 규칙','2026-10-01T00:00:00'),
('DOC_NO.PRODUCTION','PR-{yyyyMM}-{seq4}','TEXT','생산 문서번호 규칙','2026-10-01T00:00:00'),
('DOC_NO.INOUT','IO-{yyyyMM}-{seq4}','TEXT','입출고 문서번호 규칙','2026-10-01T00:00:00'),
('BACKUP.FULL_WEEKLY','1','BOOLEAN','주 1회 Full Backup 사용','2026-10-01T00:00:00');

INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'RAW','원재료',10 FROM TB_CODE_GROUP WHERE GROUP_KEY='ITEM_CATEGORY';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'SEMI','반제품',20 FROM TB_CODE_GROUP WHERE GROUP_KEY='ITEM_CATEGORY';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'FINISHED','완제품',30 FROM TB_CODE_GROUP WHERE GROUP_KEY='ITEM_CATEGORY';

INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'IN','입고',10 FROM TB_CODE_GROUP WHERE GROUP_KEY='INOUT_TYPE';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'OUT','출고',20 FROM TB_CODE_GROUP WHERE GROUP_KEY='INOUT_TYPE';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'LOSS','LOSS',30 FROM TB_CODE_GROUP WHERE GROUP_KEY='INOUT_TYPE';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'OPENING','초기재고',5 FROM TB_CODE_GROUP WHERE GROUP_KEY='INOUT_TYPE';
INSERT OR IGNORE INTO TB_CODE (CODE_GROUP_ID,CODE_KEY,CODE_NAME,SORT_ORDER)
SELECT CODE_GROUP_ID,'ADJUST','재고조정',40 FROM TB_CODE_GROUP WHERE GROUP_KEY='INOUT_TYPE';
